"""一次性导入：常用单词500 课程包 第4课~第30课（句子 + 中文翻译）。

家长手工导入了第1~3课（来源 C:\\Users\\asd\\Desktop\\english\\500\\NN.txt，
每文件 20 句、仅英文）。本脚本按相同结构导入第4~30课：每课一个 course
（第N课），20 个 sentence 条目，sort_order 0-19、difficulty 1、
source=NN.txt、unit_label 为空（同第3课的干净结构；第1/2课把每句标成
"入门单元 1..20" 是手工导入的偶发不一致，不沿用）。中文为人工逐句翻译
并内嵌（确定性、可复核）。

幂等：已存在的 course / 条目（按 english_text 判重）跳过，可重复运行。

在 VPS 上运行：
    cd /opt/MemoSeed/backend
    PYTHONPATH=/opt/MemoSeed/backend ./.venv/bin/python scripts/import_500_words_lessons.py
"""

from __future__ import annotations

import argparse

from sqlalchemy import select

from app.db.session import SessionLocal
from app.models.course import Course
from app.models.course_package import CoursePackage
from app.models.learning_item import LearningItem
from app.models.user import User

PACKAGE_NAME = "常用单词500"

# lesson_no -> [(english, chinese), ...] 每课 20 句，顺序与 NN.txt 一致
LESSONS: dict[int, list[tuple[str, str]]] = {
    4: [
        ("I have bread and an egg for breakfast.", "我早餐吃面包和一个鸡蛋。"),
        ("She likes drinking orange juice very much.", "她非常喜欢喝橙汁。"),
        ("We eat rice and vegetables for lunch.", "我们午饭吃米饭和蔬菜。"),
        ("He prefers noodles to rice.", "比起米饭，他更喜欢吃面条。"),
        ("My mother makes delicious cookies every week.", "我妈妈每周都做美味的饼干。"),
        ("They invited us to dinner at their house.", "他们邀请我们去他们家吃晚饭。"),
        ("I want to try some traditional Chinese food.", "我想尝尝传统的中国食物。"),
        ("The restaurant serves both Chinese and Western food.", "这家餐馆既供应中餐也供应西餐。"),
        ("She is learning to cook different dishes.", "她正在学做不同的菜。"),
        ("We usually have fish on Fridays.", "我们星期五通常吃鱼。"),
        ("He doesn't like spicy food at all.", "他一点也不喜欢吃辣的食物。"),
        ("I drink a glass of milk before bed.", "我睡前喝一杯牛奶。"),
        ("The smell of fresh bread fills the kitchen.", "新鲜面包的香味飘满了厨房。"),
        ("My father makes coffee every morning.", "我爸爸每天早上煮咖啡。"),
        ("We grow tomatoes in our garden.", "我们在菜园里种西红柿。"),
        ("She bought some fresh fruit at the market.", "她在市场买了一些新鲜水果。"),
        ("He is hungry after a long walk.", "走了很长的路之后，他饿了。"),
        ("I enjoy eating ice cream in summer.", "夏天我喜欢吃冰淇淋。"),
        ("We had a wonderful dinner at a new restaurant.", "我们在一家新餐馆吃了一顿很棒的晚餐。"),
        ("She taught me how to make pancakes.", "她教我做薄饼。"),
    ],
    5: [
        ("It's a sunny day today.", "今天是个晴天。"),
        ("I love walking in the rain.", "我喜欢在雨中散步。"),
        ("The snow is beautiful in winter.", "冬天的雪很美。"),
        ("Spring is the best season of the year.", "春天是一年中最好的季节。"),
        ("The weather changes quickly in autumn.", "秋天的天气变化很快。"),
        ("We often go swimming in summer.", "夏天我们经常去游泳。"),
        ("He likes to ski on snowy mountains.", "他喜欢在雪山上滑雪。"),
        ("The wind is very strong today.", "今天风很大。"),
        ("I can see colorful flowers in the garden.", "我能看到花园里五颜六色的花。"),
        ("We make a snowman together in winter.", "冬天我们一起堆雪人。"),
        ("The temperature dropped below zero last night.", "昨晚气温降到了零度以下。"),
        ("She carries an umbrella on rainy days.", "下雨天她随身带着雨伞。"),
        ("He wears sunglasses on bright days.", "阳光灿烂的日子他戴太阳镜。"),
        ("We plan to have a picnic this weekend.", "我们计划这个周末去野餐。"),
        ("The leaves fall from the trees in autumn.", "秋天树叶从树上落下来。"),
        ("I enjoy the cool breeze by the lake.", "我喜欢湖边凉爽的微风。"),
        ("The thunder scared the little boy.", "雷声把小男孩吓坏了。"),
        ("She watches the sunrise from her window.",  "她从窗口看日出。"),
        ("He likes the warm sunshine in spring.", "他喜欢春天温暖的阳光。"),
        ("We stay at home on stormy nights.", "暴风雨的夜晚我们待在家里。"),
    ],
    6: [
        ("She is interested in painting beautiful pictures.", "她对画漂亮的画很感兴趣。"),
        ("He spends much time reading books in the library.", "他花很多时间在图书馆看书。"),
        ("We go jogging in the park every morning.", "我们每天早上在公园里慢跑。"),
        ("My hobby is collecting stamps from different countries.", "我的爱好是收集各国的邮票。"),
        ("She practices the piano for two hours every day.", "她每天练两个小时钢琴。"),
        ("He joined the swimming team last summer.", "去年夏天他加入了游泳队。"),
        ("We have a basketball game this Saturday.", "这个星期六我们有一场篮球赛。"),
        ("She won the singing competition in our school.", "她赢得了我们学校的歌唱比赛。"),
        ("He enjoys playing chess with his friends.", "他喜欢和朋友们下棋。"),
        ("I am learning to draw cartoons in my free time.", "我在空闲时间学画漫画。"),
        ("She goes to the gym to keep fit.", "她去健身房锻炼身体。"),
        ("We watched a wonderful football match on TV.", "我们在电视上看了一场精彩的足球赛。"),
        ("He takes photos of beautiful flowers in the garden.", "他在花园里给美丽的花拍照。"),
        ("My sister loves dancing to the music.", "我妹妹喜欢跟着音乐跳舞。"),
        ("They often go fishing by the river on weekends.", "周末他们经常去河边钓鱼。"),
        ("She is a member of the school art club.", "她是学校美术社团的成员。"),
        ("I want to learn how to play the guitar.", "我想学弹吉他。"),
        ("He runs faster than any other student in our class.", "他比我们班其他任何同学都跑得快。"),
        ("We often climb mountains together in autumn.", "秋天我们经常一起爬山。"),
        ("She likes watching movies on weekend evenings.", "她喜欢在周末晚上看电影。"),
    ],
    7: [
        ("I went to Shanghai by plane last summer.", "去年夏天我乘飞机去了上海。"),
        ("We will take the train to Beijing tomorrow.", "明天我们将坐火车去北京。"),
        ("She prefers traveling by train because it is cheaper.", "她更喜欢坐火车旅行，因为更便宜。"),
        ("He drove his new car to the countryside.", "他开着新车去了乡下。"),
        ("We booked a room in a small hotel near the beach.", "我们在海边的一家小旅馆订了房间。"),
        ("She bought a ticket for the morning flight.", "她买了一张早班机的机票。"),
        ("He packed his suitcase the night before the trip.", "他在旅行前一晚收拾好了行李箱。"),
        ("I lost my passport during the journey abroad.", "我在国外旅行时弄丢了护照。"),
        ("She visited many famous places of interest in China.", "她参观了中国的许多著名景点。"),
        ("He took many photos during his trip to Paris.", "他在巴黎旅行时拍了很多照片。"),
        ("We stayed at a hotel with a beautiful sea view.", "我们住在一家能看到美丽海景的酒店。"),
        ("I have never been to that country before.", "我以前从未去过那个国家。"),
        ("She arrived at the airport two hours early.", "她提前两小时到达了机场。"),
        ("He will travel around Europe next month.", "他下个月将环游欧洲。"),
        ("We enjoyed the beautiful sunset on the beach.", "我们在海滩上欣赏了美丽的日落。"),
        ("I forgot to bring my camera on vacation.", "度假时我忘了带相机。"),
        ("She likes taking a walk along the beach in the evening.", "她喜欢傍晚沿着海滩散步。"),
        ("He misses his hometown while living abroad.", "他在国外生活时想念家乡。"),
        ("We plan to visit the Great Wall next week.", "我们计划下周去参观长城。"),
        ("I prefer to travel alone rather than with a group.", "比起跟团，我更喜欢独自旅行。"),
    ],
    8: [
        ("She went shopping with her mother yesterday.", "昨天她和妈妈去购物了。"),
        ("He bought a new pair of shoes for school.", "他买了一双上学穿的新鞋。"),
        ("I spent all my pocket money on books.", "我把所有的零花钱都花在买书上了。"),
        ("We can pay by credit card or cash.", "我们可以用信用卡或现金支付。"),
        ("The price of the dress is very reasonable.", "这条连衣裙的价格很合理。"),
        ("She tried on several dresses before choosing one.", "她试穿了好几条裙子才选中一条。"),
        ("He saved enough money to buy a new bike.", "他攒够了钱买一辆新自行车。"),
        ("We went to the supermarket to buy some vegetables.", "我们去超市买了一些蔬菜。"),
        ("She is looking for a cheaper one in another shop.", "她正在另一家店里找更便宜的。"),
        ("He decided to return the broken watch to the store.", "他决定把坏手表退给商店。"),
        ("I need to change some money before leaving.", "离开前我需要换一些钱。"),
        ("She compared prices before making the decision.", "她在做决定前比较了价格。"),
        ("He gave me a discount on the new shirt.", "这件新衬衫他给我打了折。"),
        ("We saw many customers waiting outside the shop.", "我们看到许多顾客在店外等候。"),
        ("She asked the shopkeeper about the size of the shoes.", "她问店主鞋子的尺码。"),
        ("He paid the bill at the restaurant yesterday.", "昨天他在餐馆结了账。"),
        ("I will save my money to buy a new computer.", "我要攒钱买一台新电脑。"),
        ("She found a beautiful dress on sale.", "她发现一条漂亮的裙子在打折。"),
        ("He carried heavy shopping bags back home.", "他提着沉重的购物袋回家。"),
        ("We bought some presents for our friends.", "我们给朋友们买了一些礼物。"),
    ],
    9: [
        ("She takes exercise every morning to stay healthy.", "她每天早上锻炼身体以保持健康。"),
        ("He has a headache and needs to see a doctor.", "他头疼，需要看医生。"),
        ("I feel much better after a good night's sleep.", "好好睡了一晚之后，我感觉好多了。"),
        ("We should drink enough water every day.", "我们每天应该喝足够的水。"),
        ("She went to the dentist to check her teeth.", "她去看牙医检查牙齿。"),
        ("He hurt his leg while playing football yesterday.", "昨天他踢足球时伤了腿。"),
        ("I have a slight cough and need some medicine.", "我有点咳嗽，需要吃点药。"),
        ("She wears glasses because she is short-sighted.", "她因为近视而戴眼镜。"),
        ("He runs every day to keep his body strong.", "他每天跑步以保持身体强壮。"),
        ("We must eat more vegetables and less meat.", "我们必须多吃蔬菜、少吃肉。"),
        ("She put a bandage on the small cut on her finger.", "她在手指的小伤口上贴了创可贴。"),
        ("He went to the hospital for a medical check.", "他去医院做体检。"),
        ("I need to rest for a few days to recover.", "我需要休息几天来恢复。"),
        ("She often has a fever in cold weather.", "天冷的时候她经常发烧。"),
        ("He takes vitamins to improve his health.", "他吃维生素来增进健康。"),
        ("We should wash our hands before meals.", "我们应该饭前洗手。"),
        ("She smiled happily and felt less tired.", "她开心地笑了，感觉没那么累了。"),
        ("He didn't eat breakfast and felt hungry at noon.", "他没吃早餐，中午觉得饿了。"),
        ("I go to bed early to have enough sleep.", "我早早睡觉，保证充足的睡眠。"),
        ("She eats an apple a day to keep the doctor away.", "她每天吃一个苹果，保持健康不生病。"),
    ],
    10: [
        ("I use my computer to do homework every day.", "我每天用电脑做作业。"),
        ("She sent an email to her friend in America.", "她给她在美国的朋友发了一封电子邮件。"),
        ("He downloaded some useful apps on his phone.", "他在手机上下载了一些有用的应用。"),
        ("We often chat with each other on the Internet.", "我们经常在网上聊天。"),
        ("She watched an interesting video online last night.", "昨晚她在网上看了一个有趣的视频。"),
        ("He bought a new smartphone for his birthday.", "他生日买了一部新智能手机。"),
        ("I learned a lot from searching the Internet.", "通过上网搜索，我学到了很多。"),
        ("She likes taking pictures with her digital camera.", "她喜欢用数码相机拍照。"),
        ("He posts his photos on social media every week.", "他每周在社交媒体上发照片。"),
        ("We use the search engine to find information quickly.", "我们用搜索引擎快速查找信息。"),
        ("She listens to music on her MP3 player.", "她用MP3播放器听音乐。"),
        ("He is learning how to type faster on the keyboard.", "他正在学习怎样在键盘上打字更快。"),
        ("I save my homework on a USB drive.", "我把作业保存在U盘里。"),
        ("She received a message from her online friend.", "她收到了网友发来的一条消息。"),
        ("He plays computer games in his free time.", "他在空闲时间玩电脑游戏。"),
        ("We video call with our relatives once a week.", "我们每周和亲戚视频通话一次。"),
        ("She bought an e-reader to read books anywhere.", "她买了一个电子阅读器，可以随时随地看书。"),
        ("He fixed the broken computer for his father.", "他帮爸爸修好了坏电脑。"),
        ("I share my location with my family on the phone.", "我在手机上和家人共享我的位置。"),
        ("She uses online maps to find her way easily.", "她用在线地图轻松找路。"),
    ],
    11: [
        ("The dog is the most loyal animal to humans.", "狗是对人类最忠诚的动物。"),
        ("I love watching birds flying in the sky.", "我喜欢看鸟儿在天空中飞翔。"),
        ("There are many kinds of animals in the zoo.", "动物园里有许多种动物。"),
        ("The tiger is the king of the forest.", "老虎是森林之王。"),
        ("We should protect wild animals and their habitat.", "我们应该保护野生动物和它们的栖息地。"),
        ("She has a cute cat as her pet.", "她养了一只可爱的猫当宠物。"),
        ("He feeds the fish in the pond every morning.", "他每天早上给池塘里的鱼喂食。"),
        ("We saw some pandas during our trip to Sichuan.", "四川之行我们看到了一些大熊猫。"),
        ("The rabbit runs fast across the field.", "兔子飞快地跑过田野。"),
        ("She has been afraid of snakes since she was a child.", "她从小就怕蛇。"),
        ("He keeps a pet dog in his house.", "他在家里养了一只宠物狗。"),
        ("We can hear frogs singing near the lake at night.", "夜晚我们能听到湖边青蛙的叫声。"),
        ("The little girl picked a flower in the garden.", "小女孩在花园里摘了一朵花。"),
        ("Butterflies fly from one flower to another.", "蝴蝶在花丛间飞来飞去。"),
        ("I like the sound of birds singing in the morning.", "我喜欢清晨鸟儿的歌声。"),
        ("She put some birdseed out for the birds.", "她放了一些鸟食给鸟儿吃。"),
        ("He takes his dog for a walk after dinner.", "晚饭后他带狗去散步。"),
        ("We often go to the forest to enjoy fresh air.", "我们经常去森林里呼吸新鲜空气。"),
        ("She watched the fish swimming in the clear water.", "她看着鱼儿在清澈的水里游来游去。"),
        ("He wants to be a zoologist when he grows up.", "他长大后想当一名动物学家。"),
    ],
    12: [
        ("We celebrate the Spring Festival with our family.", "我们和家人一起庆祝春节。"),
        ("My mother made dumplings for the New Year.", "妈妈为新年包了饺子。"),
        ("We put up red lanterns during the holiday.", "节日期间我们挂起了红灯笼。"),
        ("He received many red packets from relatives.", "他收到了亲戚给的许多红包。"),
        ("She wore a beautiful new dress on Christmas.", "圣诞节她穿了一条漂亮的新裙子。"),
        ("We had a wonderful time at the party last night.", "昨晚的聚会上我们玩得很开心。"),
        ("He sent a greeting card to his best friend.", "他给他最好的朋友寄了一张贺卡。"),
        ("She bought many presents for her family members.", "她给家人买了许多礼物。"),
        ("The whole family gathered for a big dinner.", "全家人聚在一起吃大餐。"),
        ("Children enjoy setting off fireworks on New Year's Eve.", "孩子们喜欢在除夕放烟花。"),
        ("We visited our grandparents during the holiday.", "假期我们去看望了爷爷奶奶。"),
        ("He wishes everyone a happy new year.", "他祝大家新年快乐。"),
        ("She wrote a letter to Santa Claus before Christmas.", "圣诞节前她给圣诞老人写了一封信。"),
        ("We went to see the fireworks display together.", "我们一起去看烟花表演。"),
        ("He set off fireworks with his friends at midnight.", "午夜他和朋友们一起放烟花。"),
        ("She decorated the Christmas tree with colorful lights.", "她用彩灯装饰圣诞树。"),
        ("We had a special meal at the Thanksgiving dinner.", "感恩节晚餐我们吃了一顿特别的饭。"),
        ("He traveled home to be with his family for the festival.", "他赶回家和家人一起过节。"),
        ("She danced happily at the New Year party.", "她在新年晚会上开心地跳舞。"),
        ("We enjoyed the long holiday at the beach.", "我们在海滩上度过了愉快的长假。"),
    ],
    13: [
        ("She wants to be a doctor when she grows up.", "她长大后想当一名医生。"),
        ("He dreams of becoming a scientist in the future.", "他梦想将来成为一名科学家。"),
        ("I want to work as a teacher in my hometown.", "我想在家乡当一名老师。"),
        ("My uncle is a successful businessman in the city.", "我叔叔是城里一位成功的商人。"),
        ("She decided to study medicine after high school.", "她决定高中毕业后学医。"),
        ("He works hard to achieve his dream job.", "他努力工作，想得到理想的工作。"),
        ("We visited the company to learn about different jobs.", "我们参观了那家公司，了解不同的工作。"),
        ("She applied for the position of a reporter.", "她申请了记者的职位。"),
        ("He trained as an engineer for four years.", "他接受了四年的工程师培训。"),
        ("I helped my father with work in his office.", "我在爸爸的办公室里帮他干活。"),
        ("She found a part-time job during the summer.", "暑假她找到了一份兼职工作。"),
        ("He earned some money by working in the shop.", "他靠在店里打工挣了一些钱。"),
        ("We need to study hard for our future career.", "为了未来的事业，我们需要努力学习。"),
        ("She learned how to use a computer in her company.", "她在公司里学会了使用电脑。"),
        ("He was promoted to manager last month.", "上个月他被提升为经理。"),
        ("I attended a job interview at the company.", "我参加了那家公司的求职面试。"),
        ("She received an offer from a famous university.", "她收到了一所著名大学的录取通知。"),
        ("He plans to start his own business after graduation.", "他计划毕业后自己创业。"),
        ("We discussed our future plans with the teacher.", "我们和老师讨论了未来的计划。"),
        ("She chose nursing as her career.", "她选择了护理作为她的职业。"),
    ],
    14: [
        ("She felt very happy when she got the good news.", "听到这个好消息，她非常高兴。"),
        ("He was angry with his brother for breaking the toy.", "哥哥弄坏了玩具，他很生气。"),
        ("I feel proud of my achievements this term.", "我为这学期取得的成绩感到自豪。"),
        ("She was nervous before the important speech contest.", "重要的演讲比赛前她很紧张。"),
        ("He missed his parents while studying abroad.", "在国外留学时，他想念父母。"),
        ("I was surprised to see him at the party.", "在聚会上看到他，我很惊讶。"),
        ("She felt lonely living alone in the big city.", "独自住在大城市里，她感到孤独。"),
        ("He was disappointed with the result of the game.", "他对比赛的结果很失望。"),
        ("I was deeply moved by the moving story.", "我被这个感人的故事深深打动了。"),
        ("She felt relaxed after her long vacation at the beach.", "在海滩度过长假后，她感到很放松。"),
        ("He was excited about the trip to Australia.", "澳大利亚之行让他很兴奋。"),
        ("I was scared when I heard the strange noise.", "听到那个奇怪的声音，我很害怕。"),
        ("She felt grateful for her parents' love.", "她感激父母的爱。"),
        ("He was sad to say goodbye to his old friends.",  "和老朋友们告别，他很难过。"),
        ("I was worried about my sick grandmother.", "我担心生病的奶奶。"),
        ("She felt confident after passing the difficult exam.", "通过那场很难的考试后，她很有信心。"),
        ("He couldn't hide his joy at the good news.", "听到好消息，他掩饰不住喜悦。"),
        ("I felt tired after working for a whole day.", "工作了一整天，我觉得很累。"),
        ("She became more patient after the experience.", "那次经历之后，她变得更有耐心了。"),
        ("He was ashamed of his rude behavior at school.", "他为自己在学校的粗鲁行为感到羞愧。"),
    ],
    15: [
        ("I will study harder next semester to improve my grades.", "下学期我要更努力学习，提高成绩。"),
        ("She plans to travel around the world one day.", "她计划有一天环游世界。"),
        ("He is going to learn a foreign language this summer.", "今年夏天他打算学一门外语。"),
        ("We hope to visit our grandparents next month.", "我们希望下个月去看望爷爷奶奶。"),
        ("She wants to become a famous singer in the future.", "她将来想成为一名著名的歌手。"),
        ("He decided to exercise more to stay healthy.", "他决定多运动以保持健康。"),
        ("I will save money to buy a new laptop.", "我要攒钱买一台新笔记本电脑。"),
        ("She promised to write to me every week.", "她答应每周给我写信。"),
        ("He agreed to help me with my English.", "他答应帮我学英语。"),
        ("We are looking forward to seeing the film.", "我们期待着看这部电影。"),
        ("I am determined to make my dream come true.", "我决心实现自己的梦想。"),
        ("She will take part in the speech contest.", "她将参加演讲比赛。"),
        ("He promised to return the book on time.", "他答应按时还书。"),
        ("I want to make more friends in the new school.", "我想在新学校交更多的朋友。"),
        ("She decided to change her habits to be healthier.", "她决定改变习惯，让自己更健康。"),
        ("He plans to enter the university after graduation.", "他计划毕业后上大学。"),
        ("We hope to win the match this Saturday.", "我们希望赢得本周六的比赛。"),
        ("She decided to learn how to cook this year.", "她决定今年学做饭。"),
        ("He wants to visit more countries in the future.", "他将来想去更多的国家看看。"),
        ("I will try my best to achieve my goals.", "我会尽最大努力实现我的目标。"),
    ],
    16: [
        ("Beijing is the capital city of China.", "北京是中国的首都。"),
        ("There are many tall buildings in the modern city.", "这座现代化的城市里有许多高楼。"),
        ("I live in a small town near the mountain.", "我住在山附近的一个小镇上。"),
        ("The Great Wall is one of the greatest wonders of the world.", "长城是世界上最伟大的奇迹之一。"),
        ("She enjoys living in a busy city.", "她喜欢住在繁忙的城市里。"),
        ("He visited the famous museum with his classmates.", "他和同学们参观了那座著名的博物馆。"),
        ("The library is the tallest building in our town.", "图书馆是我们镇上最高的建筑。"),
        ("We can see the beautiful lake from the window.", "从窗口我们能看到美丽的湖。"),
        ("He works in an office in the city center.", "他在市中心的一间办公室工作。"),
        ("She went to the post office to mail a letter.", "她去邮局寄了一封信。"),
        ("I usually take the subway to go to school.", "我通常坐地铁去上学。"),
        ("The hospital is not far from my apartment.", "医院离我的公寓不远。"),
        ("We walked across the busy street carefully.", "我们小心地穿过繁忙的街道。"),
        ("She visited the Palace Museum during the holiday.", "假期她参观了故宫博物院。"),
        ("He studies at one of the best universities in China.", "他在中国最好的大学之一学习。"),
        ("I will move to a bigger apartment next month.", "下个月我要搬到一套更大的公寓。"),
        ("She enjoys watching people in the busy square.", "她喜欢在热闹的广场上看人来人往。"),
        ("He took the elevator to the tenth floor.", "他乘电梯到了十楼。"),
        ("We admired the ancient architecture of the old temple.", "我们欣赏了那座古庙的古老建筑。"),
        ("She went to the bank to open a new account.", "她去银行开了一个新账户。"),
    ],
    17: [
        ("It took me three hours to finish the homework.", "我花了三个小时完成作业。"),
        ("She has lived here since she was born.", "她从出生起就住在这里。"),
        ("We will meet at three o'clock this afternoon.", "我们今天下午三点见。"),
        ("He arrived in Beijing last Tuesday morning.", "他上周二早上到达北京。"),
        ("I have been waiting for you for two hours.", "我已经等了你两个小时了。"),
        ("She will leave for Shanghai next Sunday afternoon.", "她下周日下午动身去上海。"),
        ("The film started at half past eight in the evening.", "电影晚上八点半开始。"),
        ("He has worked in this company for five years.", "他在这家公司工作五年了。"),
        ("I always get up at a quarter to seven.", "我总是六点四十五分起床。"),
        ("She visits her grandparents twice a month.", "她每个月看望爷爷奶奶两次。"),
        ("The train leaves the station at nine sharp.", "火车九点整离站。"),
        ("We have known each other since primary school.", "我们从小学起就认识了。"),
        ("He studies English every day from seven to nine.", "他每天七点到九点学英语。"),
        ("I went to bed at ten o'clock last night.", "昨晚我十点钟上床睡觉。"),
        ("She usually finishes her work before five in the afternoon.", "她通常在下午五点前完成工作。"),
        ("The meeting lasted for two hours yesterday.", "昨天的会议持续了两个小时。"),
        ("He will graduate from the university in two years.", "他两年后大学毕业。"),
        ("I saw him a few minutes ago in the library.", "几分钟前我在图书馆看到他了。"),
        ("She has been a teacher since 2010.", "她从2010年起就当老师了。"),
        ("We will have a long vacation during the summer.", "夏天我们将有一个长假。"),
    ],
    18: [
        ("She is taller than her younger sister.", "她比她妹妹高。"),
        ("He runs faster than any other boy in the class.", "他比班上其他任何男孩都跑得快。"),
        ("This book is more interesting than that one.", "这本书比那本更有趣。"),
        ("My room is smaller than my brother's.", "我的房间比我哥哥的小。"),
        ("She studies harder than most of her classmates.", "她比她的大多数同学学习更努力。"),
        ("He has more books than I do in his collection.", "他收藏的书比我多。"),
        ("Today is warmer than yesterday.", "今天比昨天暖和。"),
        ("She is the most beautiful girl in our school.", "她是我们学校最漂亮的女孩。"),
        ("He is the tallest of the three brothers.", "他是三兄弟中最高的。"),
        ("I have less money than he does at the moment.", "目前我的钱比他少。"),
        ("She is as tall as her mother now.", "她现在和她妈妈一样高了。"),
        ("He is not as old as his elder brother.", "他没有他哥哥年纪大。"),
        ("The weather is becoming colder and colder.", "天气变得越来越冷了。"),
        ("She becomes more and more beautiful every year.", "她一年比一年漂亮。"),
        ("He is the best player in the football team.", "他是足球队里最好的队员。"),
        ("This problem is more difficult than the last one.", "这道题比上一道更难。"),
        ("She has fewer friends than before.", "她的朋友比以前少了。"),
        ("He is more careful than his younger brother.", "他比他弟弟更细心。"),
        ("The movie was more boring than I expected.", "这部电影比我预想的更无聊。"),
        ("She is more confident than she was last year.", "她比去年更自信了。"),
    ],
    19: [
        ("We have a lot of fun on Saturday afternoons.", "星期六下午我们玩得很开心。"),
        ("She often goes to the cinema with her friends.", "她经常和朋友们去看电影。"),
        ("He enjoys watching TV at home on weekends.", "周末他喜欢在家看电视。"),
        ("I usually sleep late on Saturday mornings.", "星期六早上我通常睡懒觉。"),
        ("We plan to have a barbecue in the garden.", "我们计划在花园里烧烤。"),
        ("She likes shopping at the weekend market.", "她喜欢在周末市场购物。"),
        ("He plays computer games after finishing his homework.", "他做完作业后玩电脑游戏。"),
        ("We had a wonderful time at the picnic last weekend.", "上周末野餐我们玩得很开心。"),
        ("She invited her friends to her birthday party.", "她邀请朋友们参加她的生日聚会。"),
        ("He went fishing with his father last Sunday.", "上周日他和爸爸去钓鱼了。"),
        ("We took many photos during our trip.", "旅行中我们拍了很多照片。"),
        ("She went swimming in the swimming pool.", "她去游泳池游泳了。"),
        ("He joined a club to learn painting.", "他加入了一个社团学画画。"),
        ("I volunteer at the community center on weekends.", "周末我在社区中心做志愿者。"),
        ("She practices dancing for three hours every Sunday.", "她每周日练三个小时舞蹈。"),
        ("He often helps his grandparents on weekends.", "周末他经常帮爷爷奶奶干活。"),
        ("We visited the museum and learned a lot.", "我们参观了博物馆，学到了很多。"),
        ("She cooked a delicious meal for the family.", "她为家人做了一顿美味的饭。"),
        ("He read several books during the holiday.", "假期里他读了好几本书。"),
        ("I enjoy playing table tennis with my classmates.", "我喜欢和同学们打乒乓球。"),
    ],
    20: [
        ("Reading books opens my mind to the world.", "读书让我开阔眼界看世界。"),
        ("She borrowed an English novel from the library.", "她从图书馆借了一本英文小说。"),
        ("He spent a whole afternoon reading in his room.", "他在房间里看了一整个下午的书。"),
        ("I like reading stories before going to bed.", "我喜欢睡前读故事。"),
        ("She wrote a short story for the school newspaper.", "她为校报写了一篇短篇故事。"),
        ("He is fond of reading science fiction books.", "他喜欢读科幻小说。"),
        ("We discussed the meaning of the story in class.", "我们在课堂上讨论了这个故事的含义。"),
        ("She keeps a diary to record her daily life.", "她写日记记录自己的日常生活。"),
        ("He reads aloud to practice his pronunciation.", "他大声朗读来练习发音。"),
        ("I learned many new words by reading English books.", "通过读英文书，我学会了很多新单词。"),
        ("She won the first prize in the writing contest.", "她在写作比赛中获得了一等奖。"),
        ("He often reads newspapers to keep up with the news.", "他经常读报纸以了解新闻。"),
        ("We exchanged books with each other last week.", "上周我们互相交换了书。"),
        ("She likes reading about history and culture.", "她喜欢读历史和文化方面的书。"),
        ("He reads different kinds of books to learn.", "他读各种各样的书来学习。"),
        ("I often underline the important sentences in books.", "我经常在书中重要的句子下面划线。"),
        ("She cut out the article from the newspaper.", "她从报纸上剪下了那篇文章。"),
        ("He recommended a good book to me last week.", "上周他向我推荐了一本好书。"),
        ("We went to the bookshop to buy some new books.", "我们去书店买了一些新书。"),
        ("She uses a dictionary when she meets new words.", "遇到生词时她就查词典。"),
    ],
    21: [
        ("She plays the violin beautifully at the concert.", "她在音乐会上小提琴拉得很动听。"),
        ("He joined the school band last September.", "去年九月他加入了学校乐队。"),
        ("I enjoy listening to classical music in the evening.", "晚上我喜欢听古典音乐。"),
        ("She drew a beautiful picture for the art exhibition.", "她为美术展画了一幅漂亮的画。"),
        ("He performed on the stage for the first time.", "他第一次登台表演。"),
        ("We sang a famous song at the school concert.", "在学校音乐会上我们唱了一首名曲。"),
        ("She practices drawing every day after class.", "她每天课后练习画画。"),
        ("He bought a ticket to the music concert yesterday.", "昨天他买了一张音乐会的票。"),
        ("I learned how to play the guitar last year.", "去年我学会了弹吉他。"),
        ("She likes the peaceful song by that famous singer.", "她喜欢那位著名歌手唱的那首宁静的歌。"),
        ("He watched an opera at the national theater.", "他在国家大剧院看了一场歌剧。"),
        ("We visited the art gallery during the weekend.", "周末我们参观了美术馆。"),
        ("She listens to jazz music while reading.", "她一边看书一边听爵士乐。"),
        ("He is learning how to sing English songs.", "他正在学唱英文歌。"),
        ("I performed a dance at the school talent show.", "我在学校才艺秀上表演了舞蹈。"),
        ("She drew a portrait of her best friend.", "她给她最好的朋友画了一幅肖像。"),
        ("He was taught to play the piano by his mother.", "他妈妈教他弹钢琴。"),
        ("We enjoyed the wonderful concert at the town hall.", "我们在市政厅欣赏了精彩的音乐会。"),
        ("She is good at painting in watercolors.", "她擅长画水彩画。"),
        ("He created a short video about his school life.", "他制作了一个关于校园生活的短视频。"),
    ],
    22: [
        ("She often helps her mother with the housework.", "她经常帮妈妈做家务。"),
        ("He volunteers at the old people's home every weekend.", "他每个周末都去养老院做志愿者。"),
        ("I donated my old books to the school library.", "我把我的旧书捐给了学校图书馆。"),
        ("She gave her seat to an old lady on the bus.", "在公交车上，她把座位让给了一位老奶奶。"),
        ("He helped the little girl find her mother.", "他帮助小女孩找到了妈妈。"),
        ("We should be kind to people in need.", "我们应该善待有困难的人。"),
        ("She raised money for the poor children in the village.", "她为村里的贫困孩子们筹款。"),
        ("He carried the heavy bag for his grandfather.", "他帮爷爷提沉重的袋子。"),
        ("I often help my classmates with their problems.", "我经常帮助同学解决难题。"),
        ("She sent a care package to her sick friend.", "她给生病的朋友寄了一个爱心包裹。"),
        ("He picked up the rubbish from the ground.", "他从地上捡起了垃圾。"),
        ("We donated blood to the blood bank last month.", "上个月我们去血库献了血。"),
        ("She helped the old man cross the busy road.", "她扶那位老人穿过繁忙的马路。"),
        ("He bought a present for the child in the hospital.", "他给住院的孩子买了一份礼物。"),
        ("I work as a helper at the community center.", "我在社区中心当帮手。"),
        ("She often brings food to the homeless people.", "她经常给无家可归的人送食物。"),
        ("He thanked me for helping him with the work.", "他感谢我帮他完成了工作。"),
        ("We collected clothes for the victims of the flood.", "我们为洪灾灾民募集衣物。"),
        ("She is always ready to help others in need.", "她总是乐于帮助有困难的人。"),
        ("He shared his lunch with his hungry classmate.", "他和饥饿的同学分享了自己的午餐。"),
    ],
    23: [
        ("He has the habit of reading before bedtime.", "他有睡前阅读的习惯。"),
        ("She always keeps a diary of her daily life.", "她总是写日记记录日常生活。"),
        ("I usually take a shower before going to bed.", "我通常睡前洗个澡。"),
        ("He drinks a glass of water as soon as he wakes up.", "他一醒来就喝一杯水。"),
        ("She stretches her body after getting up.", "她起床后伸展身体。"),
        ("I always make my bed in the morning.", "我早上总是整理床铺。"),
        ("He spends half an hour jogging every morning.", "他每天早上慢跑半小时。"),
        ("She keeps her room clean and tidy.", "她保持房间干净整洁。"),
        ("I check my phone first thing in the morning.", "我早上第一件事就是看手机。"),
        ("He hasn't smoked since last year.", "他从去年起就戒烟了。"),
        ("She avoids eating too much sweet food.", "她避免吃太多甜食。"),
        ("He always wears a smile on his face.", "他脸上总是带着微笑。"),
        ("I never go to bed without brushing my teeth.", "我从不不刷牙就睡觉。"),
        ("She often listens to soft music to relax.", "她经常听轻音乐放松。"),
        ("He writes down his plan every evening.", "他每天晚上写下自己的计划。"),
        ("I drink a cup of tea before work every morning.", "每天早上开始工作前我喝一杯茶。"),
        ("She practices yoga three times a week.", "她每周练三次瑜伽。"),
        ("He takes notes during the English class.", "英语课上他记笔记。"),
        ("I review my lessons every night before sleeping.", "每晚睡前我都复习功课。"),
        ("She keeps a balanced diet to stay healthy.", "她保持均衡饮食以保持健康。"),
    ],
    24: [
        ("Her dream is to become a famous scientist.", "她的梦想是成为著名的科学家。"),
        ("He wants to travel to every country in the world.", "他想走遍世界上每个国家。"),
        ("I wish I could fly like a bird in the sky.", "我希望自己能像鸟儿一样在天上飞。"),
        ("She dreams of living in a beautiful small village.", "她梦想住在一个美丽的小村庄里。"),
        ("He hopes to win an Olympic gold medal one day.", "他希望有一天能赢得奥运金牌。"),
        ("I want to write a book about my experiences.", "我想写一本关于自己经历的书。"),
        ("She is determined to achieve her dream.", "她决心实现自己的梦想。"),
        ("He plans to climb the highest mountain in the world.", "他计划攀登世界上最高的山。"),
        ("I would like to learn four foreign languages.", "我想学四门外语。"),
        ("She wishes to meet her favorite singer someday.", "她希望有一天能见到她最喜欢的歌手。"),
        ("He believes that hard work leads to success.", "他相信努力会带来成功。"),
        ("I hope to visit space one day in the future.", "我希望将来有一天能去太空看看。"),
        ("She set a clear goal for her future career.", "她为未来的事业定下了明确的目标。"),
        ("He wants to start a small business after college.", "大学毕业后他想做点小生意。"),
        ("I hope to see the Northern Lights in my life.", "我希望有生之年能看到北极光。"),
        ("She worked hard to make her dream come true.", "她努力学习，让梦想成真。"),
        ("He believes in himself and never gives up.", "他相信自己，永不放弃。"),
        ("I hope my family stays healthy forever.", "我希望我的家人永远健康。"),
        ("She wants to be a famous writer one day.", "她想有一天成为著名的作家。"),
        ("He is full of hope for the future.", "他对未来充满希望。"),
    ],
    25: [
        ("I want to visit Paris to see the Eiffel Tower.", "我想去巴黎看埃菲尔铁塔。"),
        ("She dreams of going to America to study.", "她梦想去美国学习。"),
        ("He traveled to many countries during his vacation.", "假期他去了许多国家旅行。"),
        ("We learned about different cultures around the world.", "我们了解了世界各地不同的文化。"),
        ("She knows a lot about the history of England.", "她对英国的历史很了解。"),
        ("He went to Japan and tried sushi for the first time.", "他去了日本，第一次尝到了寿司。"),
        ("I have been to the Great Wall twice in my life.", "我一生中去过两次长城。"),
        ("She visited her uncle in Canada last summer.", "去年夏天她去看望了在加拿大的叔叔。"),
        ("He wants to learn about the people in Africa.", "他想了解非洲的人们。"),
        ("I am interested in the culture of ancient Egypt.", "我对古埃及文化很感兴趣。"),
        ("She has a friend from Australia who studies here.", "她有一位来自澳大利亚、在这里学习的朋友。"),
        ("He learned some French before his trip to Paris.", "去巴黎旅行前，他学了一些法语。"),
        ("We studied maps to plan our trip across Europe.", "我们研究地图来规划欧洲之行。"),
        ("She dreams of traveling across the desert alone.", "她梦想独自穿越沙漠。"),
        ("He has visited more than ten different countries.", "他去过十多个不同的国家。"),
        ("I would love to see the pyramids of Egypt.", "我很想去看看埃及的金字塔。"),
        ("She went to Korea and tried Korean barbecue.", "她去了韩国，品尝了韩国烤肉。"),
        ("He enjoys learning foreign languages in his free time.", "他喜欢在空闲时间学外语。"),
        ("I want to see the sunrise on Mount Fuji.", "我想看富士山的日出。"),
        ("She traveled around Asia during her holiday.", "假期她环游了亚洲。"),
    ],
    26: [
        ("Would you like some tea or coffee?", "你想喝点茶还是咖啡？"),
        ("May I have your name, please?", "请问你叫什么名字？"),
        ("What time does the meeting begin?", "会议几点开始？"),
        ("Could you tell me the way to the station?", "你能告诉我去车站的路吗？"),
        ("I am sorry for being late.", "对不起，我迟到了。"),
        ("Don't worry about it at all.", "完全不用担心。"),
        ("Thank you very much for your help.", "非常感谢你的帮助。"),
        ("You are welcome anytime.", "不客气，随时欢迎你。"),
        ("Have a nice day with your family.", "祝你和家人度过美好的一天。"),
        ("See you tomorrow morning.", "明天早上见。"),
        ("Let me introduce my best friend to you.", "让我把我最好的朋友介绍给你。"),
        ("How was your weekend with your grandparents?", "你和爷爷奶奶的周末过得怎么样？"),
        ("I had a great time at the party last night.", "昨晚的聚会我玩得很开心。"),
        ("Where have you been since last Friday?", "上周五以来你去哪儿了？"),
        ("I am looking for a pair of sports shoes.", "我在找一双运动鞋。"),
        ("How much does this beautiful dress cost?", "这条漂亮的裙子多少钱？"),
        ("The film begins at seven in the evening.", "电影晚上七点开始。"),
        ("I called you but you didn't answer.", "我给你打了电话，但你没接。"),
        ("Would you please open the window for me?", "请你帮我打开窗户好吗？"),
        ("I am glad to hear that good news from you.", "听到你带来的好消息，我很高兴。"),
    ],
    27: [
        ("She worked hard, and she passed the exam.", "她努力学习，通过了考试。"),
        ("He likes music, but he doesn't like dancing.", "他喜欢音乐，但不喜欢跳舞。"),
        ("I was tired, so I went to bed early.", "我累了，所以早早睡了。"),
        ("We waited for a long time, but she didn't come.", "我们等了很久，但她没有来。"),
        ("He studies English, and he speaks it well.", "他学英语，而且说得很好。"),
        ("I called him, but he was not at home.", "我给他打了电话，但他不在家。"),
        ("She is young, but she can take care of herself.", "她年纪虽小，但能照顾自己。"),
        ("He didn't feel well, so he stayed at home.", "他感觉不舒服，所以待在家里。"),
        ("I want to go swimming, and I will invite my friends.", "我想去游泳，还会邀请我的朋友们。"),
        ("We studied all night, and we finished the project.", "我们学了一整夜，完成了项目。"),
        ("He is rich, but he lives a simple life.", "他很富有，但过着简朴的生活。"),
        ("I missed the bus, so I took a taxi.", "我错过了公交车，所以打了出租车。"),
        ("She sang a song, and the audience loved it.", "她唱了一首歌，观众们都很喜欢。"),
        ("He read the book, but he didn't understand it.", "他读了这本书，但没读懂。"),
        ("I was free, so I helped my mother with the cooking.", "我有空，所以帮妈妈做饭。"),
        ("We played football, and we had great fun.", "我们踢了足球，玩得非常开心。"),
        ("She has a small cat, but she loves it very much.", "她有一只小猫，她非常爱它。"),
        ("He runs fast, but he cannot catch up with her.", "他跑得很快，但追不上她。"),
        ("I saved money, and I bought a new bicycle.", "我攒了钱，买了一辆新自行车。"),
        ("She woke up late, so she was late for school.", "她起晚了，所以上学迟到了。"),
    ],
    28: [
        ("If it rains tomorrow, we will stay at home.", "如果明天下雨，我们就待在家里。"),
        ("When I grow up, I want to be a teacher.", "等我长大了，我想当一名老师。"),
        ("Because he studied hard, he got a good grade.", "因为学习努力，他取得了好成绩。"),
        ("She was happy because she passed the test.", "她很高兴，因为她通过了测验。"),
        ("If you work harder, you will succeed.", "如果你更努力，你就会成功。"),
        ("When the bell rings, the class will begin.", "铃响的时候就开始上课。"),
        ("I will call you when I get to the station.", "我到车站的时候会给你打电话。"),
        ("She stayed up late because she had homework.", "她熬夜到很晚，因为她有作业。"),
        ("If you don't hurry, you will miss the train.", "如果你不快点，就会错过火车。"),
        ("When he comes, please give him this book.", "他来的时候，请把这本书给他。"),
        ("Because she was sick, she didn't go to school.", "因为生病了，她没去上学。"),
        ("If I have time, I will visit the museum.", "如果我有时间，我就去参观博物馆。"),
        ("He was late because the traffic was heavy.", "他迟到了，因为路上很堵。"),
        ("When spring comes, the flowers will bloom.", "春天来了，花儿就会开放。"),
        ("If you need help, just let me know.", "如果你需要帮助，就告诉我。"),
        ("She felt tired because she walked a long way.", "她觉得累，因为走了很远的路。"),
        ("When you finish, please close the window.", "你用完之后，请关上窗户。"),
        ("If he studies harder, he will do better.", "如果他学习更努力，他就会做得更好。"),
        ("Because it was cold, he wore a warm coat.", "因为天冷，他穿了一件暖和的外套。"),
        ("When I was young, I lived in the countryside.", "我小时候住在乡下。"),
    ],
    29: [
        ("The book which I bought yesterday is interesting.", "我昨天买的那本书很有趣。"),
        ("She is the girl who helped me find my way.", "她就是帮我找到路的那个女孩。"),
        ("This is the place where we first met.", "这就是我们第一次见面的地方。"),
        ("He remembered the day when he graduated.", "他记得自己毕业的那一天。"),
        ("The man who is standing there is my uncle.", "站在那里的那位男士是我叔叔。"),
        ("I will never forget the moment when I won.", "我永远不会忘记我获胜的那一刻。"),
        ("The cake which my mother made is delicious.", "我妈妈做的蛋糕很好吃。"),
        ("She told me about the city where she was born.", "她给我讲了她出生的那座城市。"),
        ("He is the student whose parents are doctors.", "他就是那个父母是医生的学生。"),
        ("The film that we watched was very moving.", "我们看的那部电影非常感人。"),
        ("I have a friend whose father is a policeman.", "我有一个朋友，他的爸爸是警察。"),
        ("The school where I study is near my home.", "我就读的学校离我家很近。"),
        ("The book that I am reading is about history.", "我正在读的这本书是关于历史的。"),
        ("He is the boy who won the competition.", "他就是赢了比赛的那个男孩。"),
        ("The girl whose bag was lost looked worried.", "丢了包的那个女孩看起来很着急。"),
        ("The house where we used to live is very old.", "我们以前住的那栋房子很旧了。"),
        ("She is the teacher who taught me English.", "她就是教我英语的那位老师。"),
        ("I lost the watch which my father gave me.", "我把爸爸送给我的手表弄丢了。"),
        ("The boy who sits next to me is my cousin.", "坐在我旁边的那个男孩是我表哥。"),
        ("She thanked the doctor who saved her life.", "她感谢了救了她一命的那位医生。"),
    ],
    30: [
        ("Practice makes perfect in the long run.", "熟能生巧。"),
        ("Where there is a will, there is a way.", "有志者，事竟成。"),
        ("It is never too late to learn something new.", "活到老，学到老。"),
        ("A friend in need is a friend indeed.", "患难见真情。"),
        ("Actions speak louder than words.", "行动胜于言语。"),
        ("Knowledge is power in the modern world.", "知识就是力量。"),
        ("Time and tide wait for no one.", "岁月不等人。"),
        ("The early bird catches the worm.", "早起的鸟儿有虫吃。"),
        ("Better late than never.", "迟做总比不做好。"),
        ("Honesty is the best policy in life.", "诚实为上策。"),
        ("Don't put off till tomorrow what you can do today.", "今日事，今日毕。"),
        ("Rome was not built in a single day.", "罗马不是一天建成的。"),
        ("Easy come, easy go.", "来得容易，去得也快。"),
        ("All work and no play makes Jack a dull boy.", "只工作不玩耍，聪明孩子也变傻。"),
        ("Reading is to the mind what exercise is to the body.", "阅读之于头脑，犹如运动之于身体。"),
        ("A good beginning is half the battle.", "良好的开端是成功的一半。"),
        ("Health is wealth above everything else.", "健康是最大的财富。"),
        ("Every man is the master of his own fate.", "每个人都是自己命运的主人。"),
        ("You are never too young to start learning.", "学习永远不嫌早。"),
        ("Two heads are better than one.", "三个臭皮匠，赛过诸葛亮。"),
    ],
}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--username", default="轩轩", help="导入到哪个用户（默认：轩轩）")
    args = parser.parse_args()

    db = SessionLocal()
    try:
        user = db.scalar(select(User).where(User.username == args.username))
        if user is None:
            raise SystemExit(f"用户不存在：{args.username}")
        package = db.scalar(
            select(CoursePackage).where(
                CoursePackage.user_id == user.id,
                CoursePackage.name == PACKAGE_NAME,
            )
        )
        if package is None:
            raise SystemExit(f"课程包不存在：{PACKAGE_NAME}")

        total_new = 0
        for lesson_no in sorted(LESSONS):
            sentences = LESSONS[lesson_no]
            assert len(sentences) == 20, f"第{lesson_no}课应为 20 句，实际 {len(sentences)}"
            course_name = f"第{lesson_no}课"
            course = db.scalar(
                select(Course).where(Course.package_id == package.id, Course.name == course_name)
            )
            if course is None:
                course = Course(user_id=user.id, package_id=package.id, name=course_name)
                db.add(course)
                db.flush()
            existing = set(
                db.scalars(
                    select(LearningItem.english_text).where(LearningItem.course_id == course.id)
                ).all()
            )
            added = 0
            for idx, (english, chinese) in enumerate(sentences):
                if english in existing:
                    continue
                db.add(
                    LearningItem(
                        user_id=user.id,
                        course_id=course.id,
                        item_type="sentence",
                        english_text=english,
                        chinese_text=chinese,
                        difficulty_level=1,
                        sort_order=idx,
                        source=f"{lesson_no:02d}.txt",
                    )
                )
                added += 1
            total_new += added
            print(f"{course_name}: 新增 {added} 句（合计 {len(existing) + added}）")
        db.commit()
        print(f"完成：共导入 {total_new} 句。")
    finally:
        db.close()


if __name__ == "__main__":
    main()
